apiVersion: v1
kind: Service
metadata:
  name: foodies-nodeport-service
spec:
  type: NodePort
  selector:
    appName: foodies
    version: "1.0"
    env: test
  ports:
  - port:  8080
    targetPort: 8080
    nodePort: 31000
  